datos:
   twitter:
      antoniodellugarea
   web:
      ajca.es
management:
   endpoints:
      enabled-by-default:
         true
      web:
         exposure:
            include:
               "*"      